load("@rules_cc//cc:defs.bzl", "cc_test")
load("//:common.bzl", "COPTS")

cc_test(
    name = "file_reader_test",
    srcs = ["file_reader_test.c"],
    copts = COPTS,
    data = glob(["data/**"]),
    deps = [
        "//src/reader",
        "//test/runtime",
    ],
)

cc_test(
    name = "mem_reader_test",
    srcs = ["mem_reader_test.c"],
    copts = COPTS,
    deps = [
        "//src/reader",
        "//test/runtime",
    ],
)
