load("@rules_cc//cc:defs.bzl", "cc_test")
load("//:common.bzl", "COPTS")

cc_test(
    name = "buf_file_test",
    srcs = ["buf_file_test.c"],
    copts = COPTS,
    data = ["file.bin"],
    deps = [
        "//src/buf",
        "//test/runtime",
    ],
)

cc_test(
    name = "buf_mem_test",
    srcs = ["buf_mem_test.c"],
    copts = COPTS,
    deps = [
        "//src/buf",
        "//test/runtime",
    ],
)
